/* PocketPal — private, local-first personal finance */
const STORAGE_KEY = 'pocketpal-v1';
const CATEGORIES = {Food:['🍜','#fff1e8'],Transport:['🚕','#eef2ff'],Shopping:['🛍️','#fdf2f8'],Entertainment:['🎬','#f5f3ff'],Health:['✚','#ecfdf5'],Education:['📚','#eff6ff'],Salary:['💼','#ecfdf5'],Freelance:['✦','#fef3c7'],Investment:['📈','#ecfeff'],Gift:['🎁','#fdf2f8'],Travel:['✈️','#eff6ff'],Others:['◌','#f1f5f9']};
const defaultState = {transactions:[],goals:[],settings:{theme:'light',currency:'INR',monthlyBudget:0,dailyLimit:0,notifications:false,name:'Alex Patel'},lastActive:''};
let state = loadState(), charts = {}, activePeriod = 'all';
const $ = s => document.querySelector(s), $$ = s => [...document.querySelectorAll(s)];
const today = () => new Date().toISOString().slice(0,10);
function loadState(){try{return {...defaultState,...JSON.parse(localStorage.getItem(STORAGE_KEY)),settings:{...defaultState.settings,...(JSON.parse(localStorage.getItem(STORAGE_KEY))?.settings||{})}}}catch{return structuredClone(defaultState)}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));}
function money(n){return new Intl.NumberFormat('en-IN',{style:'currency',currency:state.settings.currency,maximumFractionDigits:0}).format(Number(n||0));}
function escapeHTML(v=''){const d=document.createElement('div');d.textContent=v;return d.innerHTML}
function categoryMarkup(category){const [icon,color]=CATEGORIES[category]||CATEGORIES.Others;return `<span class="category-icon" style="background:${color}">${icon}</span>`}
function toast(message,type='success'){const el=document.createElement('div');el.className=`toast ${type}`;el.textContent=message;$('#toastRegion').append(el);setTimeout(()=>el.remove(),2800)}
function uid(){return `${Date.now()}-${Math.random().toString(16).slice(2)}`}
function dateText(date){return new Date(`${date}T12:00:00`).toLocaleDateString('en-IN',{day:'numeric',month:'short',year:new Date().getFullYear()!==new Date(`${date}T12:00:00`).getFullYear()?'numeric':undefined})}
function totals(items=state.transactions){return items.reduce((a,t)=>{a[t.type]+=Number(t.amount);return a},{income:0,expense:0})}
function isInPeriod(t,p){const date=new Date(`${t.date}T12:00:00`),now=new Date();if(p==='all')return true;if(p==='day')return t.date===today();if(p==='week'){const start=new Date();start.setDate(now.getDate()-6);start.setHours(0,0,0,0);return date>=start}if(p==='month')return date.getMonth()===now.getMonth()&&date.getFullYear()===now.getFullYear();return date.getFullYear()===now.getFullYear()}
function renderHome(){const total=totals(), balance=total.income-total.expense;$('#availableBalance').textContent=money(balance);$('#incomeTotal').textContent=money(total.income);$('#expenseTotal').textContent=money(total.expense);$('#savingsTotal').textContent=money(Math.max(0,balance));const spentToday=state.transactions.filter(t=>t.type==='expense'&&t.date===today()).reduce((s,t)=>s+Number(t.amount),0),limit=state.settings.dailyLimit;$('#dailySafe').textContent=limit?money(Math.max(0,limit-spentToday)):money(0);$('#dailyDetail').textContent=limit?`${money(spentToday)} spent of ${money(limit)} today`:'Set a daily limit in profile';const budget=state.settings.monthlyBudget,monthExpense=state.transactions.filter(t=>t.type==='expense'&&isInPeriod(t,'month')).reduce((s,t)=>s+Number(t.amount),0),remaining=budget-monthExpense,pct=budget?Math.min(100,Math.round(monthExpense/budget*100)):0;$('.ring').style.setProperty('--progress',`${pct}%`);$('#budgetPercent').textContent=`${pct}%`;$('#budgetRemaining').textContent=budget?`${money(Math.max(0,remaining))} left`:'No budget set';$('#budgetCaption').textContent=budget?`of ${money(budget)} monthly budget`:'Tap Edit to set your monthly plan';$('#budgetStatus').textContent=budget?`${money(monthExpense)} spent this month`:'Make your plan count';renderTransactionList($('#recentTransactions'),state.transactions.slice().sort(sortLatest).slice(0,4),true)}
function sortLatest(a,b){return b.date.localeCompare(a.date)||b.createdAt-a.createdAt}
function transactionHTML(t){return `<article class="transaction-item" data-id="${t.id}" tabindex="0" role="button" aria-label="Edit ${escapeHTML(t.description||t.category)}"><div>${categoryMarkup(t.category)}</div><div class="transaction-info"><strong>${escapeHTML(t.description||t.category)}</strong><span>${escapeHTML(t.category)} · ${dateText(t.date)}</span></div><span class="amount ${t.type}">${t.type==='income'?'+':'−'}${money(t.amount)}</span></article>`}
function renderTransactionList(el,items,compact=false){el.innerHTML=items.length?items.map(transactionHTML).join(''):`<div class="empty-state"><i>${compact?'⌁':'◌'}</i><strong>${compact?'Your activity will appear here':'No transactions found'}</strong><p>${compact?'Add your first income or expense to begin.':'Try changing your filters or add a new transaction.'}</p></div>`;el.querySelectorAll('.transaction-item').forEach(node=>{node.onclick=()=>openTransactionModal(state.transactions.find(t=>t.id===node.dataset.id));node.onkeydown=e=>{if(e.key==='Enter')node.click()}})}
function getFilteredTransactions(){let list=state.transactions.filter(t=>isInPeriod(t,activePeriod));const q=$('#transactionSearch').value.trim().toLowerCase(),type=$('#typeFilter').value,cat=$('#categoryFilter').value,month=$('#monthFilter').value;if(q)list=list.filter(t=>`${t.category} ${t.description}`.toLowerCase().includes(q));if(type!=='all')list=list.filter(t=>t.type===type);if(cat!=='all')list=list.filter(t=>t.category===cat);if(month)list=list.filter(t=>t.date.startsWith(month));return list.sort(sortLatest)}
function renderTransactions(){renderTransactionList($('#transactionList'),getFilteredTransactions())}
function renderGoals(){const el=$('#goalsList');el.innerHTML=state.goals.length?state.goals.map(g=>{const pct=Math.min(100,Math.round(g.current/g.target*100));return `<article class="goal-card"><div class="goal-top"><div class="goal-icon">${escapeHTML(g.icon||'◎')}</div><div><strong>${escapeHTML(g.name)}</strong><span>${money(g.current)} of ${money(g.target)}</span></div><button class="goal-actions" data-goal-id="${g.id}" aria-label="Edit ${escapeHTML(g.name)}">•••</button></div><div class="progress"><span style="width:${pct}%"></span></div><div class="goal-bottom"><span>${pct}% complete</span><span>${money(Math.max(0,g.target-g.current))} to go</span></div></article>`}).join(''):`<div class="empty-state"><i>◎</i><strong>Start a savings goal</strong><p>Turn the things you want into a plan you can see.</p><button class="text-button" id="emptyGoal">Create a goal</button></div>`;el.querySelectorAll('[data-goal-id]').forEach(b=>b.onclick=()=>openGoalModal(state.goals.find(g=>g.id===b.dataset.goalId)));$('#emptyGoal')?.addEventListener('click',()=>openGoalModal());const transactionDates=[...new Set(state.transactions.map(t=>t.date))].sort().reverse();let streak=0,d=new Date();while(transactionDates.includes(d.toISOString().slice(0,10))){streak++;d.setDate(d.getDate()-1)}$('#streakCount').textContent=`${streak} day streak`;$('#badgeFirst').classList.toggle('earned',state.transactions.length>0);$('#badgeBudget').classList.toggle('earned',state.settings.monthlyBudget>0);$('#badgeGoal').classList.toggle('earned',state.goals.length>0)}
function chartData(period){const items=state.transactions.filter(t=>isInPeriod(t,period));return {items,expenses:items.filter(t=>t.type==='expense'),income:items.filter(t=>t.type==='income')}}
function destroyCharts(){Object.values(charts).forEach(c=>c.destroy());charts={}}
function renderAnalytics(){if(!window.Chart)return;destroyCharts();const {items,expenses}=chartData($('#analyticsPeriod').value), largest=expenses.slice().sort((a,b)=>b.amount-a.amount)[0], avg=expenses.length?expenses.reduce((s,t)=>s+Number(t.amount),0)/expenses.length:0;$('#largestExpense').textContent=largest?money(largest.amount):'—';$('#largestExpenseName').textContent=largest?largest.description||largest.category:'No expenses yet';$('#averageSpend').textContent=money(avg);$('#transactionCount').textContent=items.length;const colors=['#6366f1','#10b981','#f59e0b','#ec4899','#06b6d4','#8b5cf6','#f97316'];const cats={};expenses.forEach(t=>cats[t.category]=(cats[t.category]||0)+Number(t.amount));const labels=Object.keys(cats),values=Object.values(cats);charts.category=new Chart($('#categoryChart'),{type:'doughnut',data:{labels:labels.length?labels:['No expenses'],datasets:[{data:values.length?values:[1],backgroundColor:values.length?colors:['#e9ecf3'],borderWidth:0,borderRadius:6}]},options:{cutout:'70%',plugins:{legend:{display:false}}}});$('#categoryLegend').innerHTML=labels.map((l,i)=>`<span class="legend-item"><i style="background:${colors[i%colors.length]}"></i>${escapeHTML(l)}</span>`).join('')||'<span class="legend-item">Add expenses to see categories</span>';const months=[];for(let i=5;i>=0;i--){const d=new Date();d.setMonth(d.getMonth()-i);months.push({key:`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`,label:d.toLocaleDateString('en',{month:'short'})})}const dataset=type=>months.map(m=>state.transactions.filter(t=>t.type===type&&t.date.startsWith(m.key)).reduce((s,t)=>s+Number(t.amount),0));charts.bar=new Chart($('#incomeExpenseChart'),{type:'bar',data:{labels:months.map(m=>m.label),datasets:[{label:'Income',data:dataset('income'),backgroundColor:'#10b981',borderRadius:7},{label:'Expenses',data:dataset('expense'),backgroundColor:'#818cf8',borderRadius:7}]},options:chartOptions(true)});const days=[];for(let i=6;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);days.push({key:d.toISOString().slice(0,10),label:d.toLocaleDateString('en',{weekday:'short'})})}charts.line=new Chart($('#dailyChart'),{type:'line',data:{labels:days.map(d=>d.label),datasets:[{data:days.map(d=>state.transactions.filter(t=>t.type==='expense'&&t.date===d.key).reduce((s,t)=>s+Number(t.amount),0)),borderColor:'#f59e0b',backgroundColor:'#f59e0b20',fill:true,tension:.4,pointRadius:3,pointBackgroundColor:'#f59e0b'}]},options:chartOptions(false)})}
function chartOptions(legend){return {responsive:true,maintainAspectRatio:true,plugins:{legend:{display:legend,labels:{boxWidth:8,font:{family:'Inter',size:10}}}},scales:{x:{grid:{display:false},ticks:{font:{size:10}}},y:{grid:{color:'rgba(148,163,184,.13)'},ticks:{font:{size:10},callback:v=>money(v)}}}}}
function openModal(content){$('#modalContent').innerHTML=content;$('#modalBackdrop').classList.add('open');$('#modalBackdrop').setAttribute('aria-hidden','false');setTimeout(()=>$('#modalContent input, #modalContent select')?.focus(),50)}
function closeModal(){$('#modalBackdrop').classList.remove('open');$('#modalBackdrop').setAttribute('aria-hidden','true')}
function categoryOptions(selected=''){return Object.keys(CATEGORIES).map(c=>`<option ${c===selected?'selected':''}>${c}</option>`).join('')}
function openTransactionModal(edit=null,forceType='expense'){const t=edit||{type:forceType,amount:'',category:forceType==='income'?'Salary':'Food',description:'',date:today()};openModal(`<h2>${edit?'Edit transaction':'Add transaction'}</h2><p>${edit?'Keep your records neat and current.':'Every small detail makes your money story clearer.'}</p><form id="transactionForm" class="form-grid"><input type="hidden" id="transactionType" value="${t.type}"><div class="type-picker"><button type="button" class="${t.type==='expense'?'selected expense-type':''}" data-type="expense">− Expense</button><button type="button" class="${t.type==='income'?'selected income-type':''}" data-type="income">+ Income</button></div><div class="field"><label for="amount">Amount</label><input required id="amount" type="number" inputmode="decimal" min="0.01" step="0.01" placeholder="0" value="${t.amount}"></div><div class="field"><label for="category">Category</label><select id="category">${categoryOptions(t.category)}</select></div><div class="field"><label for="description">Description</label><input id="description" maxlength="60" placeholder="What was this for?" value="${escapeHTML(t.description)}"></div><div class="field"><label for="transactionDate">Date</label><input required id="transactionDate" type="date" value="${t.date}"></div>${edit?`<div class="form-actions"><button type="button" class="outline-button" id="deleteTransaction">Delete</button><button class="modal-submit">Save changes</button></div>`:'<button class="modal-submit">Save transaction</button>'}</form>`);$$('.type-picker button').forEach(b=>b.onclick=()=>{const type=b.dataset.type;$('#transactionType').value=type;$$('.type-picker button').forEach(x=>x.className=x.dataset.type===type?`selected ${type}-type`:'');$('#category').value=type==='income'?'Salary':'Food'});$('#transactionForm').onsubmit=e=>{e.preventDefault();const amount=Number($('#amount').value);if(!amount||amount<=0)return toast('Enter an amount greater than zero','error');const item={id:edit?.id||uid(),type:$('#transactionType').value,amount,category:$('#category').value,description:$('#description').value.trim(),date:$('#transactionDate').value,createdAt:edit?.createdAt||Date.now()};if(edit)state.transactions=state.transactions.map(x=>x.id===edit.id?item:x);else state.transactions.push(item);save();closeModal();renderAll();toast(edit?'Transaction updated':'Transaction saved')};$('#deleteTransaction')?.addEventListener('click',()=>confirmAction('Delete transaction?','This transaction will be permanently removed.',()=>{state.transactions=state.transactions.filter(x=>x.id!==edit.id);save();closeModal();renderAll();toast('Transaction deleted')}))}
function openGoalModal(edit=null){const g=edit||{name:'',target:'',current:'',icon:'◎'};openModal(`<h2>${edit?'Edit goal':'Create a goal'}</h2><p>Give every rupee a purpose.</p><form id="goalForm" class="form-grid"><div class="field"><label for="goalName">Goal name</label><input required id="goalName" maxlength="40" placeholder="e.g. Japan trip" value="${escapeHTML(g.name)}"></div><div class="field"><label for="goalTarget">Target amount</label><input required id="goalTarget" type="number" min="1" inputmode="decimal" value="${g.target}"></div><div class="field"><label for="goalCurrent">Saved so far</label><input required id="goalCurrent" type="number" min="0" inputmode="decimal" value="${g.current}"></div>${edit?`<div class="form-actions"><button type="button" class="outline-button" id="deleteGoal">Delete</button><button class="modal-submit">Save goal</button></div>`:'<button class="modal-submit">Create goal</button>'}</form>`);$('#goalForm').onsubmit=e=>{e.preventDefault();const target=Number($('#goalTarget').value),current=Number($('#goalCurrent').value);if(!target||target<1||current<0)return toast('Check the amounts and try again','error');const item={id:edit?.id||uid(),name:$('#goalName').value.trim(),target,current,icon:'◎'};if(edit)state.goals=state.goals.map(x=>x.id===edit.id?item:x);else state.goals.push(item);save();closeModal();renderGoals();toast(edit?'Goal updated':'New goal created')};$('#deleteGoal')?.addEventListener('click',()=>confirmAction('Delete goal?','Your saved progress will be removed.',()=>{state.goals=state.goals.filter(x=>x.id!==edit.id);save();closeModal();renderGoals();toast('Goal deleted')}))}
function openBudgetModal(kind='budget'){const isBudget=kind==='budget',key=isBudget?'monthlyBudget':'dailyLimit',title=isBudget?'Monthly budget':'Daily spending limit';openModal(`<h2>${title}</h2><p>${isBudget?'Set a monthly ceiling you feel good about.':'We’ll show how much is safe to spend today.'}</p><form id="limitForm" class="form-grid"><div class="field"><label for="limitAmount">Amount</label><input required id="limitAmount" type="number" min="0" inputmode="decimal" value="${state.settings[key]||''}" placeholder="0"></div><button class="modal-submit">Save ${isBudget?'budget':'limit'}</button></form>`);$('#limitForm').onsubmit=e=>{e.preventDefault();state.settings[key]=Number($('#limitAmount').value);save();closeModal();renderAll();toast(`${title} updated`)}}
function confirmAction(title,text,action){openModal(`<h2>${title}</h2><p>${text}</p><div class="form-actions"><button class="outline-button" id="cancelConfirm">Cancel</button><button class="modal-submit danger" id="acceptConfirm">Delete</button></div>`);$('#cancelConfirm').onclick=closeModal;$('#acceptConfirm').onclick=action}
function renderProfile(){$('#themeToggle').checked=state.settings.theme==='dark';$('#currencySelect').value=state.settings.currency;$('#notificationsToggle').checked=state.settings.notifications;$('#settingsBudget').textContent=state.settings.monthlyBudget?money(state.settings.monthlyBudget):'Not set';$('#settingsDailyLimit').textContent=state.settings.dailyLimit?money(state.settings.dailyLimit):'Not set';$('#profile-title').textContent=state.settings.name;$('#home-title').innerHTML=`${escapeHTML(state.settings.name.split(' ')[0])} <span>✦</span>`}
function renderAll(){renderHome();renderTransactions();renderGoals();renderProfile();if($('#analytics-screen').classList.contains('active'))renderAnalytics()}
function navigate(name){$$('.screen').forEach(s=>s.classList.toggle('active',s.id===`${name}-screen`));$$('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===name));if(name==='analytics')renderAnalytics();window.scrollTo({top:0,behavior:'smooth'})}
function downloadCSV(){if(!state.transactions.length)return toast('There are no transactions to export','error');const data=[['Date','Type','Category','Description','Amount'],...state.transactions.map(t=>[t.date,t.type,t.category,t.description,t.amount])].map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type:'text/csv'}));a.download=`pocketpal-transactions-${today()}.csv`;a.click();URL.revokeObjectURL(a.href);toast('CSV export downloaded')}
function importBackup(file){const reader=new FileReader();reader.onload=()=>{try{const parsed=JSON.parse(reader.result);if(!Array.isArray(parsed.transactions)||!Array.isArray(parsed.goals)||!parsed.settings)throw Error();confirmAction('Import backup?','This will replace current PocketPal data.',()=>{state={...defaultState,...parsed,settings:{...defaultState.settings,...parsed.settings}};save();closeModal();applyTheme();renderAll();toast('Backup imported')})}catch{toast('That file is not a PocketPal backup','error')}};reader.readAsText(file)}
function applyTheme(){document.body.classList.toggle('dark',state.settings.theme==='dark');document.querySelector('meta[name="theme-color"]').content=state.settings.theme==='dark'?'#101322':'#6366f1'}
function seed(){if(state.transactions.length||state.goals.length)return;state.transactions=[{id:uid(),type:'income',amount:45000,category:'Salary',description:'Monthly salary',date:today(),createdAt:Date.now()-5},{id:uid(),type:'expense',amount:680,category:'Food',description:'Lunch with friends',date:today(),createdAt:Date.now()-4},{id:uid(),type:'expense',amount:1200,category:'Shopping',description:'Groceries',date:today(),createdAt:Date.now()-3}];state.settings.monthlyBudget=18000;state.settings.dailyLimit=1000;save()}
function bind(){document.addEventListener('click',e=>{const nav=e.target.closest('[data-nav]');if(nav)navigate(nav.dataset.nav);const action=e.target.closest('[data-action]');if(action){if(action.dataset.action==='goal')navigate('goals');else if(action.dataset.action==='transfer')toast('Transfers can be recorded as an expense and income pair');else openTransactionModal(null,action.dataset.action)}});$('#fab').onclick=()=>openTransactionModal();$('#modalClose').onclick=closeModal;$('#modalBackdrop').onclick=e=>{if(e.target===$('#modalBackdrop'))closeModal()};$('#profileShortcut').onclick=()=>navigate('profile');$('#editBudget').onclick=()=>openBudgetModal();$('#budgetSettings').onclick=()=>openBudgetModal();$('#dailyLimitSettings').onclick=()=>openBudgetModal('daily');$('#addGoalButton').onclick=()=>openGoalModal();$('#filterToggle').onclick=()=>$('#filterPanel').classList.toggle('open');$('#transactionSearch').oninput=renderTransactions;['typeFilter','categoryFilter','monthFilter'].forEach(id=>$('#'+id).onchange=renderTransactions);$$('.period-tabs button').forEach(b=>b.onclick=()=>{activePeriod=b.dataset.period;$$('.period-tabs button').forEach(x=>x.classList.toggle('active',x===b));renderTransactions()});$('#analyticsPeriod').onchange=renderAnalytics;$('#themeToggle').onchange=e=>{state.settings.theme=e.target.checked?'dark':'light';save();applyTheme();renderAnalytics()};$('#currencySelect').onchange=e=>{state.settings.currency=e.target.value;save();renderAll()};$('#notificationsToggle').onchange=e=>{state.settings.notifications=e.target.checked;save();toast(e.target.checked?'Budget reminders enabled':'Notifications disabled')};$('#exportData').onclick=downloadCSV;$('#importData').onchange=e=>e.target.files[0]&&importBackup(e.target.files[0]);$('#clearData').onclick=()=>confirmAction('Clear all PocketPal data?','This permanently removes transactions, goals and preferences.',()=>{state=structuredClone(defaultState);save();closeModal();applyTheme();renderAll();toast('All PocketPal data cleared')});$('#editName').onclick=()=>{const name=prompt('Your name',state.settings.name);if(name?.trim()){state.settings.name=name.trim();save();renderProfile();toast('Profile updated')}};document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()})}
function init(){seed();applyTheme();$('#categoryFilter').innerHTML='<option value="all">All categories</option>'+categoryOptions();bind();renderAll();if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('service-worker.js').catch(()=>{}))}init();
